### ISSUE TITLE
[Blueprints, 02-at-scale] Spot Instance Architecture Best Practices

### ISSUE THREAD

**Issue by carlosrodlop** [cloudbees/terraform-aws-cloudbees-ci-eks-addon#41]
Sport Architecture Best Practices per https://aws.amazon.com/blogs/compute/cost-optimization-and-resilience-eks-with-spot-instances/. It is applied into Jenkins Infra here: https://github.com/jenkins-infra/aws/blob/main/cik8s-cluster.tf

See also EKS Spot Best Practice: https://repost.aws/knowledge-center/eks-spot-instance-best-practices

**Comment by jglick** [comment]
Please be sure to read https://docs.cloudbees.com/docs/cloudbees-ci/latest/pipelines/restart-aborted-builds#_restarting_pipeline_node_blocks_using_the_retry_option

**Comment by carlosrodlop** [comment]
I will also include Timeout closure
